FROM alpine:3.20

RUN apk add --no-cache openssh \
    && adduser -D -s /bin/sh tunnel \
    && echo 'tunnel:disabled-password' | chpasswd \
    && mkdir -p /home/tunnel/.ssh /run/sshd \
    && chown -R tunnel:tunnel /home/tunnel

COPY sshd_config /etc/ssh/sshd_config
COPY entrypoint.sh /usr/local/bin/tunnelctl-test-sshd

RUN chmod 0755 /usr/local/bin/tunnelctl-test-sshd

EXPOSE 22
ENTRYPOINT ["/usr/local/bin/tunnelctl-test-sshd"]
